// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjFztJr_Jz6Ii9E0Aku9IDsgdTCQVC7MM',
    appId: '1:638147490303:web:957fecb82b85d9679d37ca',
    messagingSenderId: '638147490303',
    projectId: 'fincenter-chile',
    authDomain: 'fincenter-chile.firebaseapp.com',
    databaseURL: 'https://fincenter-chile-default-rtdb.firebaseio.com',
    storageBucket: 'fincenter-chile.appspot.com',
    measurementId: 'G-3JHTTF1QWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQWMD1W6KF4ge5oHOEtu60DeVRdr29CaM',
    appId: '1:638147490303:android:7c187cf202862af19d37ca',
    messagingSenderId: '638147490303',
    projectId: 'fincenter-chile',
    databaseURL: 'https://fincenter-chile-default-rtdb.firebaseio.com',
    storageBucket: 'fincenter-chile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV3uLGgpN5hTgosiGeJoe-LTp0cTqOuvc',
    appId: '1:638147490303:ios:aec5ea8747369bec9d37ca',
    messagingSenderId: '638147490303',
    projectId: 'fincenter-chile',
    databaseURL: 'https://fincenter-chile-default-rtdb.firebaseio.com',
    storageBucket: 'fincenter-chile.appspot.com',
    iosBundleId: 'fincenter.cl.app',
  );

}